image: debian

build:
  before_script:
    - apt-get update -qq && apt-get install --no-install-recommends -y
          gcc
          make
          clang
          pkg-config
          libsdl2-dev
          libyaml-dev
          libcyaml-dev
          libsdl2-image-dev
          libwebsockets-dev
  script:
    - make -Bj4 CC=clang
    - make -Bj4 CC=gcc
