name: CI
on: [push]
jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt-get install packages
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               gcc
               make
               pkg-config
               libsdl2-dev
               libyaml-dev
               libsdl2-image-dev
               libwebsockets-dev
    - name: install libcyaml
      run: |
           git clone https://github.com/tlsa/libcyaml.git &&
           sudo make -C libcyaml install
    - name: build
      run: make

  linux-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt-get install packages
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               make
               clang
               pkg-config
               libsdl2-dev
               libyaml-dev
               libsdl2-image-dev
               libwebsockets-dev
    - name: install libcyaml
      run: |
           git clone https://github.com/tlsa/libcyaml.git &&
           sudo make -C libcyaml install
    - name: build
      run: make CC=clang

  linux-scan-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt-get install packages
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               make
               pkg-config
               clang-tools
               libsdl2-dev
               libyaml-dev
               libsdl2-image-dev
               libwebsockets-dev
    - name: install libcyaml
      run: |
           git clone https://github.com/tlsa/libcyaml.git &&
           sudo make -C libcyaml install
    - name: build
      run: scan-build make
